planmeal_homepage:
    path:     /{annee}{semaine}
    defaults: { _controller: PlanmealBundle:Repas:index, annee:2016, semaine: 1 }
    requirements:
        semaine: \d+
        annee: \d{4}

planmeal_semaine_suivante:
    path:    /annee/{annee}/semaine/{semaine}
    defaults: { _controller: PlanmealBundle:Repas:semaineSuivante }
    requirements:
        semaine: \d+
        annee: \d{4}

planmeal_parametres_index:
    path:    /parametres 
    defaults: { _controller: PlanmealBundle:Parametres:index }

planmeal_type_ajouter:
    path:    /parametres/type/ajouter 
    defaults: { _controller: PlanmealBundle:Parametres:typeAjouter }

planmeal_type_editer:
    path:    /parametres/type/editer/{id}
    defaults: { _controller: PlanmealBundle:Parametres:typeEditer }
    requirements:
        id: \d+

planmeal_type_supprimer:
    path:    /parametres/type/supprimer/{id}
    defaults: { _controller: PlanmealBundle:Parametres:typeSupprimer }
    requirements:
        id: \d+

planmeal_plat_ajouter:
    path: /parametres/plat/ajouter
    defaults: { _controller: PlanmealBundle:Parametres:platAjouter }

planmeal_plat_editer:
    path: /parametres/plat/editer/{id}
    defaults: { _controller: PlanmealBundle:Parametres:platEditer }
    requirements:
        id: \d+

planmeal_plat_supprimer:
    path: /parametres/plat/supprimer/{id}
    defaults: { _controller: PlanmealBundle:Parametres:platSupprimer }
    requirements:
        id: \d+
