planmeal_homepage:
    path:     /
    defaults: { _controller: PlanmealBundle:Repas:index }

planmeal_semaine_suivante:
    path:    /annee/{annee}/semaine/{semaine}
    defaults: { _controller: PlanmealBundle:Repas:semaineSuivante }
    requirements:
        semaine: \d+
        annee: \d{4}

planmeal_repas_planifier:
    path:    /planifier/{page}
    defaults: { _controller:PlanmealBundle:Repas:planifier, page: 1 }
    requirements:
        page: \d+

planmeal_repas_ajouter:
    path:    /planifier/repas/ajouter
    defaults: { _controller:PlanmealBundle:Repas:ajouter }

planmeal_repas_editer:
    path:    /planifier/repas/editer/{id}
    defaults: { _controller:PlanmealBundle:Repas:editer }
    requirements:
        id: \d+

planmeal_repas_supprimer:
    path:    /planifier/repas/supprimer/{id}
    defaults: { _controller:PlanmealBundle:Repas:supprimer }
    requirements:
        id: \d+

planmeal_repas_copier:
    path:    /planifier/repas/copier/{id}
    defaults: { _controller:PlanmealBundle:Repas:copier }
    requirements:
        id: \d+

planmeal_parametres_index:
    path:    /parametres 
    defaults: { _controller: PlanmealBundle:Parametres:index }

planmeal_type_ajouter:
    path:    /parametres/type/ajouter 
    defaults: { _controller: PlanmealBundle:Parametres:typeAjouter }

planmeal_type_editer:
    path:    /parametres/type/editer/{id}
    defaults: { _controller: PlanmealBundle:Parametres:typeEditer }
    requirements:
        id: \d+

planmeal_type_supprimer:
    path:    /parametres/type/supprimer/{id}
    defaults: { _controller: PlanmealBundle:Parametres:typeSupprimer }
    requirements:
        id: \d+

planmeal_plat_ajouter:
    path: /parametres/plat/ajouter
    defaults: { _controller: PlanmealBundle:Parametres:platAjouter }

planmeal_plat_editer:
    path: /parametres/plat/editer/{id}
    defaults: { _controller: PlanmealBundle:Parametres:platEditer }
    requirements:
        id: \d+

planmeal_plat_supprimer:
    path: /parametres/plat/supprimer/{id}
    defaults: { _controller: PlanmealBundle:Parametres:platSupprimer }
    requirements:
        id: \d+

planmeal_test:
    path: /test/{id}
    defaults: { _controller: PlanmealBundle:Repas:test }
    requirements:
        id: \d+

planmeal_statistiques_index:
    path: /statistiques
    defaults: { _controller: PlanmealBundle:Statistiques:index }
