<?php

namespace PlanmealBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;


/**
 * PlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function getPlats()
	{
		$qb = $this->createQueryBuilder('p')
			->orderBy('p.nbreUtilisation', 'DESC')
			->addOrderBy('p.dateUtilisation', 'DESC')
			->getQuery()
		;

		return $qb->getResult();
	}


}
