<?php

namespace PlanmealBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * RepasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepasRepository extends \Doctrine\ORM\EntityRepository
{

	public function findRepas($annee, $semaine)
	{
		$qb = $this->createQueryBuilder('r')
			->where('r.annee = :annee')
			->setParameter('annee', $annee)
			->andWhere('r.semaine = :semaine')
			->setParameter('semaine', $semaine)
			->orderBy('r.date', 'ASC')
			->getQuery()
		;

		return $qb->getResult();
	}
}

