<?php

namespace PlanmealBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * RepasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepasRepository extends \Doctrine\ORM\EntityRepository
{

	public function findRepas($annee, $semaine)
	{
		$qb = $this->createQueryBuilder('r')
			->where('r.annee = :annee')
			->setParameter('annee', $annee)
			->andWhere('r.semaine = :semaine')
			->setParameter('semaine', $semaine)
			->orderBy('r.date', 'ASC')
			->getQuery()
		;

		return $qb->getResult();
	}

	public function findDatePlat($id)
	{
		$qb = $this->createQueryBuilder('r')
			->select('r.date')
			->leftJoin('r.plats', 'p')
			->where('p.id = :id')
			->setParameter('id', $id)
			->orderBy('r.date', 'DESC')
			->setMaxResults(1)
			->getQuery()
		;

		return $qb->getOneOrNullResult();
	}

	public function countPlat($id)
	{
		$qb = $this->createQueryBuilder('r')
			->leftJoin('r.plats', 'p')
			->addSelect('p')
			->where('p.id = :id')
			->setParameter('id', $id)
			->select('count(r.id)')
			->getQuery()
		;

		return $qb->getSingleScalarResult();
	}

	public function getRepas($page, $nbPerPage)
	{
		$query = $this->createQueryBuilder('r')
		->leftJoin('r.plats', 'p')
		->addSelect('p')
		->orderBy('r.date', 'DESC')
		->getQuery()
		;

		$query
		->setFirstResult(($page-1) * $nbPerPage)
		->setMaxResults($nbPerPage)
		;

		// Ne pas oublier le use correspondant
		return new Paginator($query, true);
	}


}

